import Head from 'next/head'
import Posts from './components/posts';
import { Container, Button, Modal, Grid } from 'semantic-ui-react'
import { useState } from 'react';
import PostsModal from './components/posts-modal';


export default function Home() {
  //Variables
  const [openModal, setOpenModal] = useState(false);
  const [selectedItem, setSelectedItem] = useState(null);
  const [results, setResults] = useState([]);

  return (
    <div className="home">
      <Container>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
    
        <Container textAlign='center'>
          <Grid>
            <Grid.Row>
              <Grid.Column>
                <h1 style={{borderBottom: '2px solid #dddfd4', color: 'white', fontSize: '40px'}}>POSTS</h1>
              </Grid.Column>
            </Grid.Row>
            <Grid.Row>
              <Grid.Column textAlign='right'>
                <Button color='blue' onClick={() => setOpenModal(true)}>Agregar</Button>
              </Grid.Column>
            </Grid.Row>
            <Grid.Row>
              <Grid.Column>
                <Posts results={results} setResults={setResults} setSelectedItem={setSelectedItem} setOpenModal={setOpenModal} />
              </Grid.Column>
            </Grid.Row>
          </Grid>
        </Container>
      </Container>

      <Modal
          onClose={() => setOpenModal(false)}
          onOpen={() => setOpenModal(true)}
          open={openModal}
      >
      <Modal.Header>POST</Modal.Header>
      <Modal.Content>
          <PostsModal 
            results={results}
            setResults={setResults} 
            item={selectedItem} 
            closeModal={setOpenModal} 
            setSelectedItem={setSelectedItem} 
            setOpenModal={setOpenModal}
          ></PostsModal>
      </Modal.Content>
      </Modal>
    </div>
  )
}